defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: ce19b56f51c3b3ec807f36dfef041828dbd2ea66757299b28b0e33dc3346a830b230bc81d60c04892a2655f46ebb1a5475c0f47f3ea0df555d8c6ebac87d2ca5
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.9.2/index.cjs'

yarnPath: .yarn/releases/yarn-4.0.0-rc.46.cjs
