defaultSemverRangePrefix: ''
enableGlobalCache: true
nmMode: hardlinks-global
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - checksum: 0f32e7b2ab1a5128157f6b236a4cc061655bffbe41a1ed84441e4eb07caac0839b013e19cd1a065ce92c29b8eb1f530a613acd3594625108190a61b64612c019
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.8.7/index.min.cjs
yarnPath: .yarn/releases/yarn-4.0.0-rc.39.cjs
