defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: 38e9c07e39ad26ceca2aad81e352f9827d3f08608a396e7286ee684b0551208b9043ba43811e5757e32867999023c982b719e6ae981cffdf2e48ba0aa42b77ef
    path: .yarn/plugins/plugin-auto-install.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v2.0.2/index.cjs'

yarnPath: .yarn/releases/yarn-4.5.1.cjs
