@startuml
title: Test Class Diagram
namespace TestA {
    class A1 {
        -int privateField
        +String publicField
        -void privateMethod(argumentX: String, argumentY: String, argumentZ: int)
        +int publicMethod(argumentX: String, argumentY: String)
    }

    class A2 {
        - privateObject: Object
        +int publicMethod(argumentX: String, argumentY: String, argumentZ: Object)
    }

    class A3 {
        Object publicMethodToConvertObject(argumentZ: Object)
    }

    A1 <|-right- A2
    A2 -right-> A3
}

namespace TestB {
    class B1 {
        -int privateField
        +String publicField
        -void privateMethod(argumentX: String, argumentY: String, argumentZ: double)
        +int publicMethod(argumentX: String, argumentY: String)
    }

    class B2 {
        - privateObject: Object
        +int publicMethod(argumentX: String, argumentY: String, argumentZ: Object)
    }

    class B3 {
        Object publicMethodToConvertObject(argumentZ: Object)
    }

    B1 <|-right- B2
    B2 -right-> B3
}
@enduml
