@startuml
title: Test Class Diagram
namespace Test {
    class A {
        -int privateField
        +String publicField
        -void privateMethod(argumentX: String, argumentY: String, argumentZ: int)
        +int publicMethod(argumentX: String, argumentY: String)
    }

    class B {
        - privateObject: Object
        +int publicMethod(argumentX: String, argumentY: String, argumentZ: Object)
    }

    class C {
        Object publicMethodToConvertObject(argumentZ: Object)
    }

    A <|-right- B
    B -right-> C
}
@enduml
