@startuml
!includesub subincludedState.pu!sub
state State1
state State2

[*] -> State1
State1 -> IncludedState1
IncludedState1 -> IncludedState2
IncludedState2 -> State2
State2 -> [*]

IngoredIncludedState

@enduml
