name: Add ready issue to GitHub project
on:
  issues:
    types:
      - labeled
jobs:
  add-ready-issue-to-project:
    uses: WillBooster/reusable-workflows/.github/workflows/add-issue-to-project.yml@main
    with:
      labeled: 'ready :rocket:'
    secrets:
      GH_PROJECT_URL: https://github.com/orgs/WillBoosterLab/projects/5
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
