name: Release

on:
  push:
    branches:
      - 'release'

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate dot env
        run: |
          echo '${{ secrets.DOT_ENV }}' > .env
      - name: Read version files
        run: |
          echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Show environment information
        run: |
          echo "node: $(node -v)"
          echo "yarn: $(yarn -v)"
      - uses: actions/cache@v2
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn build
      - run: yarn release
